### ISSUE TITLE
Issue with  updating a document

### ISSUE THREAD

**Issue by mariamgarchagudashvili** [identixone/fastapi_contrib#116]
Hi, I am having trouble to update a document.  
My model:
```
class MyModel(MongoDBTimeStampedModel):
    id: UUID
    other: str
```
Usage:
```
MyModel.update_one(
     {'id': UUID(id)},
     update={
            '$set': { 'other' : 'something'}
        }
)
```

Is it a bug in passing `kwargs`  to  `await collection.update_one(
            filter_kwargs, kwargs, session=session
        )` should not it be `await collection.update_one(
            filter_kwargs, **kwargs, session=session
        )` or am I getting something wrong? 
Ref: [Source code](https://github.com/identixone/fastapi_contrib/blob/c3c70f5c94f31cdfbe3018d54fdf66650bd11269/fastapi_contrib/db/client.py#L88)

**Comment by levchik** [comment]
Hi, @mariamgarchagudashvili 

You're right, kwargs are the params that are passed through to actual `pymongo`'s own `update_one`:

So the pymongo syntax:

```python
db.collection.update_one({'x': 1}, {'$inc': {'x': 3}})
```

It takes two dicts: first are the dict with filters, and the second is the actual update statement.

Usage of models `update_one` in `fastapi_contrib` is:
```python
await Model.update_one(filter_kwargs={"id": 1}, id=2)
```

Note that you need to be specific with the filter_kwargs keyword in order to correctly separate filters and update kwargs.

Inside of this `Model`'s statement we do actual call to collection:

```python
res = await collection.update_one(
    filter_kwargs, kwargs, session=session
)
```

Here, filter_kwargs and kwargs (as accepted with **kwargs) are dicts, so I assume the code inside is correct.

Back to your code, I think that changing it to something like the following would solve the issue:

```python
MyModel.update_one(
     filter_kwargs={'id': UUID(id)},
     other='something'
)
```

or with more complex statement:

```python
MyModel.update_one(
     filter_kwargs={'id': UUID(id)},
    **{'$set': { 'other' : 'something'}}
)
```

**Comment by mariamgarchagudashvili** [comment]
Hi @levchik ,
Thanks a lot for clarifying. It worked :)

**Comment by levchik** [comment]
No worries, @mariamgarchagudashvili 

I'm closing this issue now, if you have new questions, please open a new issue. Thanks.
