### ISSUE TITLE
consider using configurator for settings store

### ISSUE THREAD

**Issue by cjw296** [identixone/fastapi_contrib#80]
Reading https://github.com/identixone/fastapi_contrib/blob/master/fastapi_contrib/conf.py#L73 - you may find https://configurator.readthedocs.io/en/latest/ to be of interest.

In particular https://configurator.readthedocs.io/en/latest/patterns.html#global-configuration-object.

If you have any questions, please ping me on here :-)

**Comment by levchik** [comment]
This might actually make sense, thanks for sharing the lib. I'll look at how to connect configurator instead of the current solution and perhaps we might implement it in the new major version (at the moment I have several more projects that use the configuration system that is now in contrib, so the process of moving is going to be quite slow)

**Comment by cjw296** [comment]
I'd hope configurator would slot in quite easily, if you find anything that makes it tricky to switch in, I'd be interested in what could be done from the configurator side to make it easier :-)

**Comment by levchik** [comment]
I've been using pydantic settings class for quite a while now, and I think that we should not add new dependency to tangle configuration management. Since pydantic's settings is solving the problem and, in fact, is a part of the library we use in this package anyway, we should consider switching only for some features that could be useful and are missing in pydantic.

So yeah, if you have any new thoughts on exactly how adding the proposed library will help to make the project better, please feel free to write a comment. Thanks!

**Comment by cjw296** [comment]
each to their own :-)
